apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master
  labels:
    app: hadoop
    component: hadoop-master
spec:
  containers:
  - name: hadoop-namenode
    image: amnrz/hadoop:1.0
    ports:
    - containerPort: 50070
    - containerPort: 8088