apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
spec:
  selector:
    app: hadoop
    component: namenode
  ports:
    - name: "webhdfs"
      protocol: TCP
      port: 50070
      targetPort: 50070
    - name: "cluster"
      protocol: TCP
      port: 8088
      targetPort: 8088